# Site
repository: sproogen/jameswgrant
favicon: images/favicon.ico

version: 2

# Personal info
name: 张曦月
title: 武汉大学新闻与传播学院研一在读
email: xxxxxxxxxxxxxxxxxxxx

# Social links
twitter_username: sproogen
github_username:  sproogen
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: jameswgrant
linkedin_username: jameswgrant
# pinterest_username:
# youtube_username:

# About Section
# about_title: About Me
about_profile_image: images/jg2.jpg
about_content: |
  武汉大学本硕，预备党员，武汉大学《学“习”演说家》比赛连续两届冠军，武汉大学青年讲师团成员，湖北科普作家协会会员，AI视频创作者，自媒体爱好者，
  平台发布武汉大学系列AI视频超20万浏览量，收到湖北日报、九派新闻等多家媒体采访。

content:
  - title: 背景经历
    layout: list
    content:
      - layout: left
        border: weak
        title: 智谱AI实习
        sub_title: 做了xxxxxxxxxxxxxxxxxx
        caption:  2024 5 - 2024 6
        description: |
          我做了xxxxxxxx，收获了xxxxxxxxxxxxxxxxxxxxxx

      - layout: left
        border: weak
        title: 快手实习
        sub_title: 做了xxxxxxxxxxxxxxxx
        caption: xxxxxx -xxxxxxxxxxxxxx
        description: |
          在这边吃的很好xxxxxxxxxxxxxxxxxxx


  - title: 教育经历
    layout: list
    content:
      - title: 武汉大学本科
        sub_title: 新闻与传播
        caption: 2020 - 2024
        description: |
          本科阶段我学习了xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    content:
      - title: 武汉大学硕士
        sub_title: 新闻与传播
        caption: 2024 - 2026
        description: |
          正在学习xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          

  - title: 平时的兴趣爱好
    layout: text
    content: | # this will include new lines to allow paragraphs
      嗯我平时喜欢xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
